# Generated by Django 5.1.1 on 2024-10-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_hover',
        ),
    ]
