# Generated by Django 5.1.1 on 2024-09-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
